org: bobsingor
app: whitepaper-serverless-pdf2images
service: whitepaper-serverless-pdf2images
 
provider:
 name: aws
 runtime: nodejs12.x
 cfnRole: arn:aws:iam::330026732917:role/cfnRole

functions:
 upload:
  handler: handler.hello
  events: 
   - s3:
      bucket: testbucket
      event: s3:ObjectCreated:*
      rules:
        - suffix: .pdf