org: bobsingor
app: whitepaper-serverless-pdf2images
service: whitepaper-serverless-pdf2images
 
provider:
 name: aws
 runtime: nodejs12.x

functions:
 upload:
  handler: handler.hello
  events: 
   - s3:
      bucket: assets.whitepaper-staging.com
      event: s3:ObjectCreated:*
      rules:
        - suffix: .pdf
      existing: true